loglevel: Debug
write-directory: output
services:
  my-project:
    plugin: pvtr-github-repo
    test-suites:
      - dev
      # - maturity_1
      # - maturity_2
      # - maturity_3
    vars:
      owner: ossf
      repo: security-insights-spec
      token: $GITHUB_TOKEN
